### ISSUE TITLE
Move to sonartype maven central

### ISSUE THREAD

**Issue by triplem** [triplem/gradle-by-example#1]
Since jcenter bintray is sunsetting, we do need to move from jcenter() to mavenCentral(). 

This depends on https://github.com/Kotlin/kotlinx.html/issues/173, which is a dependency of detekt (see https://github.com/detekt/detekt/issues/3461).

**Comment by androiddevcoding** [comment]
How do we fix the mistake now?

**Comment by triplem** [comment]
Hm, just wait for a new version of the upstream project (kotlinx.html)?

**Comment by androiddevcoding** [comment]
> Хм, просто дождитесь новой версии апстрима (kotlinx.html)?

How to make it work detekt?

**Comment by triplem** [comment]
Guess you should really comment on the upstream project, and not here, which is a playground for myself.
